### ISSUE TITLE
[Register add-on in translation system]: msEdgeDiscardAnnouncements

### ISSUE THREAD

**Issue by nvdaes** [nvaccess/mrconfig#100]
### Add-on name

MSEdgeDiscardAnnouncements

### Add-on maintainer

@beqabeqa473

### Stable branch

- [X] Stable branch exists in add-on repo

**Comment by seanbudd** [comment]
This done now

**Comment by seanbudd** [comment]
This seems to be registered with the incorrect casing.
The repository is cased as "MSEdgeDiscardAnnouncements".
[https://github.com/beqabeqa473/MSEdgeDiscardAnnouncements/](https://github.com/beqabeqa473/MSEdgeDiscardAnnouncements/releases/download/v0.4/MSEdgeDiscardAnnouncements-v0.4.nvda-addon)

**Comment by nvdaes** [comment]
I"ll see if the fork should be renamed according to Beqa"s repo and will rename it if needed, in nvdaaddons organization.

**Comment by nvdaes** [comment]
@seanbudd , I think that the add-on name needs to be updated in automatic.crontab.

**Comment by seanbudd** [comment]
This has been done now, following the steps here: https://github.com/nvaccess/mrconfig/blob/master/docs/commonIssues.md#po-file-missing
