### ISSUE TITLE
[Register add-on in translation system]: NVDA Dev & Test Toolbox

### ISSUE THREAD

**Issue by CyrilleB79** [nvaccess/mrconfig#102]
### Add-on name

nvdaDevTestToolbox

### Add-on maintainer

@CyrilleB79

### Stable branch

- [X] Stable branch exists in add-on repo

**Comment by nvdaes** [comment]
Hi Cyrille, I think it's better to rename the forked repo since GitHub Actions seems not to build the pot file. Can I rename it removing dashes? The template for this issue requests for the add-on name assuming that it's equal to the add-on repo name.

**Comment by CyrilleB79** [comment]
OK to rename the fork, no problem for me.

For next times, when creating the fork, you may want to add as a requirement that the name of the fork should be the add-on's name, what is not always the case for the original repository.

**Comment by nvdaes** [comment]
Hi Cyrille, I've renamed the forked repo. Please close and reopen this issue so that GitHub Actions check if the pot file can be built.

**Comment by CyrilleB79** [comment]
Closing and reopening to trigger workflow.

**Comment by CyrilleB79** [comment]
Hi @seanbudd 
Could you please validate this add-on for the translation ssytem, as well as other ones waiting for it?
Many thanks!

**Comment by seanbudd** [comment]
This done now

**Comment by CyrilleB79** [comment]
Thanks!
