### ISSUE TITLE
Thunderbird+: Translations work is not transferred to SVN repo

### ISSUE THREAD

**Issue by CyrilleB79** [nvaccess/mrconfig#103]
Translation has been requested befor May 20th for Thunderbird+, e.g. for French, Spanish, Italian. See the following SVN commits:
```
es: 73982; Actions: Action column; Author: jmdaweb; Date: mardi 16 mai 2023 08:49:28; Message: Es: requested ThunderbirdPlus translation
fr: 73990; Actions: Action column; Author: blindhelp; Date: mercredi 17 mai 2023 10:08:17; Message: Fr: requested ThunderbirdPlus translation
it: 74026; Actions: Action column; Author: drein; Date: vendredi 19 mai 2023 14:25:57; Message: updated settings
```

It's more than a week that they have been requested but the work to do has not arrived in SVN.

Could you please investigate why it is blocked?

Thanks.

Cc @RPTools-org

**Comment by seanbudd** [comment]
I've forwarded an email with the error log to your address. I'll see if there's something we can do to unblock this on our end as well.

**Comment by seanbudd** [comment]
Seems like it's related to this documented issue: https://github.com/nvaccess/mrconfig/blob/master/docs/commonIssues.md#po-file-missing

**Comment by seanbudd** [comment]
should `ThunderbirdPlus` be re-registered as `thunderbirdPlus` or should the `.pot` files be renamed to match casing?

**Comment by CyrilleB79** [comment]
The add-on's name is now "thunderbirdPlus", with lowercase t.

Thus the standard is to generate "thunderbirdPlus.pot" with lowercase t as done today.

Thus, I imagine that the add-on should be re-registered with the new name?

Also, maybe the name of nvdaaddon's fork should match the add-on's name, at least, that's what was done for NVDA Dev & Test Toolbox.
Cc @nvdaes for information, confirmation and actions if needed.

**Comment by nvdaes** [comment]
Hello, I think we should register this with the new name. I'll do it now.

**Comment by nvdaes** [comment]
Hi @CyrilleB79  and @seanbudd : I¡ve requested registration for thunderbirdPlus in issue #105 . The pot file has been build successfully.

**Comment by nvdaes** [comment]
Ah, I have renamed the fork repo in nvdaaddons organization to thunderbirdPlus

2023-06-14 15:26 GMT+02:00, Noelia Ruiz Martínez ***@***.***>:

**Comment by seanbudd** [comment]
This should be fixed now
