### ISSUE TITLE
[Register add-on in translation system]: Event Tracker

### ISSUE THREAD

**Issue by XLTechie** [nvaccess/mrconfig#104]
### Add-on name

evtTracker

### Add-on maintainer

opensourcesys

### Stable branch

- [X] Stable branch exists in add-on repo

**Comment by XLTechie** [comment]
A [bug](https://github.com/nvdaaddons/addonTemplate/pull/29) in the [add-on template](https://github.com/nvdaaddons/addonTemplate) caused scons to fail in the check for stable branch workflow. Attempting to make it run again.

**Comment by seanbudd** [comment]
This done now

**Comment by XLTechie** [comment]
Thanks @seanbudd.
