### ISSUE TITLE
[Register add-on in translation system]: rdAccess

### ISSUE THREAD

**Issue by LeonarddeR** [nvaccess/mrconfig#109]
### Add-on name

rdAccess

### Add-on maintainer

@leonardder

### Stable branch

- [X] Stable branch exists in add-on repo

**Comment by LeonarddeR** [comment]
Note, this is a rename of the nvdaRd add-on which can be removed from the system.

**Comment by seanbudd** [comment]
This should be done now, using the process in https://github.com/nvaccess/mrconfig/blob/master/docs/commonIssues.md#po-file-missing

**Comment by LeonarddeR** [comment]
Thank you!
