### ISSUE TITLE
[Register add-on in translation system]: MathCAT

### ISSUE THREAD

**Issue by nvdaes** [nvaccess/mrconfig#110]
### Add-on name

MathCAT

### Add-on maintainer

@NSoiffer

### Stable branch

- [X] Stable branch exists in add-on repo

**Comment by seanbudd** [comment]
The add-on has been registered, but there are some encoding issues with MathCAT, cc @nsoiffer

```
scons: Reading SConscript files ...
scons: done reading SConscript files.
scons: Building targets ...
Generating pot file MathCAT.pot
xgettext: Non-ASCII comment at or before addon/globalPlugins/MathCAT/MathCAT.py:8.
          Please specify the source encoding through --from-code or through a comment
          as specified in http://www.python.org/peps/pep-0263.html.

scons: *** [MathCAT.pot] Error 1
scons: building terminated because of errors.
mr addon2svn: command failed

mr addon2svn: finished (1 failed)
```

**Comment by nvdaes** [comment]
The mentioned problem should be fixed in 
https://github.com/NSoiffer/MathCATForPython/commit/fa458cd0029d6da16088e32ca11e4d1691331493

I've been invited by Neil as a collaborator to his repo for tasks like this one. Please let us know if the problem persists.

**Comment by nvdaes** [comment]
@seanbudd , seems that some kind of problem persists since translations haven't been merged for this add-on. Can you check this please?
Thanks.

**Comment by seanbudd** [comment]
There's been another issue:

```
mr addon2svn: /home/nvdal10n/mr/addons/MathCAT
Running addon2svn for MathCAT
Already on 'stable'
Your branch is up to date with 'origin/stable'.
HEAD is now at fa458cd Add coding declaration
scons: Reading SConscript files ...
scons: done reading SConscript files.
scons: Building targets ...
Generating pot file MathCAT.pot
xgettext: Non-ASCII string at addon/globalPlugins/MathCAT/MathCATPreferences.py:74.
          Please specify the source encoding through --from-code or through a comment
          as specified in http://www.python.org/peps/pep-0263.html.

scons: *** [MathCAT.pot] Error 1
scons: building terminated because of errors.
mr addon2svn: command failed
```

**Comment by NSoiffer** [comment]
I pushed the fix. I hope to build a new MathCAT later tonight.

**Comment by nvdaes** [comment]
Thanks Sean: Neil has fixed the coding declaration and I've merged the 
code to the stable branch, so translations should be merged properly 
next Friday.

**Comment by seanbudd** [comment]
I've confirmed that translations appear to be working now
