### ISSUE TITLE
[Register add-on in translation system]: tonysEnhancements

### ISSUE THREAD

**Issue by nvdaes** [nvaccess/mrconfig#111]
### Add-on name

tonysEnhancements

### Add-on maintainer

@cary-rowen

### Stable branch

- [X] Stable branch exists in add-on repo

**Comment by nvdaes** [comment]
@cary-rowen , please keep account that code with translatable messages needs to be placed in the stable branch of the repo forked in nvdaaddons organization, and updated documentation should be placed on the website. Then you can merge the stable branch to the main branch of your maintainedrepo. GitHub Actions are often used for this. You can see for example one of my add-ons like clipContentsDesigner in nvdaes account for examples, and feel free to ask any other questions.

**Comment by seanbudd** [comment]
This should be done now
