### ISSUE TITLE
NVDA Dev & Test Toolbox - No translation generted

### ISSUE THREAD

**Issue by CyrilleB79** [nvaccess/mrconfig#113]
Last translations of NVDA Dev & Test Toolbox are not included in the stable branch for this add-on.

E.g. SVN commit 77334 dated October 6th, 2023 is not included in the stable branch.

Could you please have a look?

Thanks.

**Comment by seanbudd** [comment]
this appears to be fixed now

**Comment by CyrilleB79** [comment]
Do not know when and how it has been fixed... Or if it's a mistake on my side.

Anyway, all is OK now. Thanks.
