### ISSUE TITLE
Translation status page not available anymore

### ISSUE THREAD

**Issue by CyrilleB79** [nvaccess/mrconfig#115]
The page that was used to track the translation of NVDA and add-ons is not working anymore.

URL: https://addons.nvda-project.org/poStatus.html

CrowdIn already tracks the translation of nvda.po. But for add-on translation, restoring this page would be helpful. Thanks.

**Comment by michaelDCurran** [comment]
poStatus.html is back up and running again. Apologies this broke when nvda.po was removed from the system. The logic that generates this page has taken this into account now.

**Comment by CyrilleB79** [comment]
Many thanks for the very quick fix!
