### ISSUE TITLE
[Register add-on in translation system]: instantTranslate

### ISSUE THREAD

**Issue by beqabeqa473** [nvaccess/mrconfig#116]
### Add-on name

instantTranslate

### Add-on maintainer

beqabeqa473

### Stable branch

- [X] Stable branch exists in add-on repo

**Comment by CyrilleB79** [comment]
Hi @beqabeqa473 

But the add-on is actually already in the translation system.
And there is [a fork](https://github.com/nvdaaddons/instantTranslate) in nvdaaddons; or actually yours is the fork.

Could you clarify why you have opened this ticket?

**Comment by beqabeqa473** [comment]
it was disabled because of error in translations and @seanbudd asked me to create an issue.

**Comment by nvdaes** [comment]
Now I have access to the l10n server to register add-ons.
@seanbudd ,if I should do anything for this add-on, let me know.

**Comment by seanbudd** [comment]
@beqabeqa473 - can you please link information to this communication. I'm not sure what you are referring to

**Comment by beqabeqa473** [comment]
https://github.com/beqabeqa473/instantTranslate/issues/15

**Comment by seanbudd** [comment]
Thanks - @nvdaes - you can reenable this by uncommenting the relevant line in automatic.crontab. Ensure to push any changes to the crontab to this repo. I would encourage testing that the translation command works for the add-on by running it in the console before committing any changes.

**Comment by seanbudd** [comment]
See this line: https://github.com/nvaccess/mrconfig/blob/master/automatic.crontab#L96

**Comment by nvdaes** [comment]
> @nvdaes - you can reenable this by uncommenting the relevant line in automatic.crontab. Ensure to push any changes to the crontab to this repo. I would encourage testing that the translation command works for the add-on by running it in the console before committing any changes.

Thanks @seanbudd. I'll do it after job, in about 9 or 10 hours.
Before registering add-ons, I usually clone them and do: `scons pot mergePot` 
After registration I run the following command logged in the server:

`/home/nvdal10n/mr/scripts/addonTranslationUpdates.sh instantTranslate`, but I don't get any relevant feedback to see if automatic.crontab is really working.

**Comment by seanbudd** [comment]
That process seems fine to me - any issues with crontab will get emailed out when it happens

**Comment by nvdaes** [comment]
Thanks, years ago I received a lot of emails from Cron Daemon. I don't know if I'm subscribed there, but if you think that this is working, it's OK for me.
I'm noticing that translators seem not to add new registered add-ons to translate. Seems that Assembla is not sending notifications when add-ons are registered or when the documentation is submitted to SVN.

**Comment by nvdaes** [comment]
Hello, seems that messages cannot be merged properly.

This is the error when I try to perform the corresponding automatic.crontab command:

```
 committing changes                                                              
 Sending        ko/add-ons/instantTranslate/nvda.po                              
 Transmitting file data .done                                                    
 Committing transaction...                                                       
 Committed revision 79705.                                                       
 ky wants instantTranslate: 0                                                    
 lt wants instantTranslate: 0                                                    
 mk wants instantTranslate: 0                                                    
 mn wants instantTranslate: 1                                                    
 Already available for translation, merging in new messages.                     
 svn status                                                                      
 mn/add-ons/instantTranslate/nvda.po:207: duplicate message definition...        
 mn/add-ons/instantTranslate/nvda.po:205: ...this is the location of the first de
 finition                                                                        
 msgmerge: found 1 fatal error                                                   
 mr addon2svn: command failed                                                    
```

@beqabeqa473, can you fix this in SVN repo?
Thanks.

**Comment by nvdaes** [comment]
I'm trying to fix failures in this add-on. I'll remove the mn po file from the stable branch of GitHub and try to provide messages again for this language. If this doesn't work I'll revert changes.

**Comment by nvdaes** [comment]
Seems there's nothing I can do to fix this. The mentioned file is not present. Sorry.

**Comment by nvdaes** [comment]
Finally, seems that I have been able to fix the issue with this add-on, and now it contain l10n updates in the stable branch of the fork in nvdaaddons.
Let's wai until Friday to confirm that automatic.crontab works as expected.

**Comment by nvdaes** [comment]
I'll close this now as completed: new translations have been received, available on the stable branch of the nvdaaddons fork, and the server hasn't notified about errors.
