### ISSUE TITLE
[Register add-on in translation system]: wordNav

### ISSUE THREAD

**Issue by nvdaes** [nvaccess/mrconfig#121]
### Add-on name

wordNav

### Add-on maintainer

@mltony

### Stable branch

- [X] Stable branch exists in add-on repo

**Comment by nvdaes** [comment]
This is completed.
@mltony and @cary-rowen have write access to wordNav repo in nvdaaddons organization.

**Comment by cary-rowen** [comment]
Thanks @nvdaes
