### ISSUE TITLE
[Register add-on in translation system]: objWatcher

### ISSUE THREAD

**Issue by nvdaes** [nvaccess/mrconfig#124]
### Add-on name

objWatcher

### Add-on maintainer

@cary-rowen

### Stable branch

- [X] Stable branch exists in add-on repo

**Comment by cary-rowen** [comment]
When this issue was opened, there was no stable branch in the add-on's repository, but now it is.
Will this be a problem?

**Comment by nvdaes** [comment]
@cary-rowen , this is not a problem. I added a stable branch on the nvdaaddons fork before registration.
The only possible problem is that existing translations cause merge conflicts when translators request the add-on, but in this case we'll try to manage this.
I've invited you to the fork so you can push changes to the stable branch for new messages. Please accept the invitation.
I've send the documentation to svn (reflected on the website) so it appears on the system. I've fixed a typo: an asterisk without a space in the changelog, to fix the format. Now you can update the documentation in svn and the stable branch on the nvdaaddons fork.
Let's close this issue as completed since the add-on is now registered.

**Comment by cary-rowen** [comment]
OK, Thanks a lot @nvdaes
