### ISSUE TITLE
Use master branch instead of stable to receive add-on translations

### ISSUE THREAD

**Issue by nvdaes** [nvaccess/mrconfig#16]
Hello, in case add-on authors need to send pull request to a repo to submit translations, please consider to use just master branch instead of stable, which maybe an extra step not needed.
I'd like to mention @Abdel792, since yesterday he created a PR requesting an add-on (pre-release) on the add-ons website, and perhaps he's interested in provide feedback about this proposal. I think that the review process for add-ons is not in place for now, but for example if the created PR was reviewed and merged into master, in the current system we need to create an extra branch named stable to receive translations.
For reference, his PR is at

https://github.com/nvdaaddons/mp3DirectCut/pull/1

Thanks

**Comment by feerrenrut** [comment]
While I agree that the system shouldn't dictate the branch to be used to receive translations, I'd like to avoid making changes to this system. We intend to replace this system with a more flexible approach in the future, unfortunately I don't currently have a timeline.
