### ISSUE TITLE
Improve update of webpages on add-ons website

### ISSUE THREAD

**Issue by nvdaes** [nvaccess/mrconfig#17]
Currently, every person with access to Assembla repo can make changes to the add-ons website. This means that add-ons can be posted using link skipping addonFiles repo. Also, when an add-on is updated on the website, documentation needs to be updated separately, with an elapsed time since addonFile pull request are merged by @NVAccess  until someone, probably add-on authors, can update the documentation on the website to be translated into different languages.
I think that we may provide a link to documentation, and Assembla repo shouldn't be touched to send it to avoid changing links skipping addonFiles.

**Comment by feerrenrut** [comment]
I hope that the add-on website will be updated to automatically pull data from the addon-submissions repo. It should then never have to be manually updated. Perhaps as a start we can add a couple of addons to the repo, and then work can start on creating a new addon website. I'll put forward a proposal for the change to addon translation process soon, that should complete the picture.

**Comment by nvdaes** [comment]
This is great! In case you want to add real add-ons, I created a PR for placeMarkers 15.-0 in addonFiles repo, and I released 13.-0 dev for clipContentsDesigner. If you want me to send a PR with these add-ons to the submision repo, let me know, or you may prefer to add not real add-ons yourself for testing. Also, @josephsl may want to coordinate this work in case the addonTemplate needs some changes. I"m worried about new proposals for markdown extensions, in case they cannot be used in the website. If they are usable, much better, but I remember an addon that included javascript code in the documentation and we need to know what kind of format must be used, if any.

**Comment by feerrenrut** [comment]
Here is the overview of the new translation system for anyone watching this issue https://github.com/nvaccess/translationSystem

**Comment by nvdaes** [comment]
Thanks @feerrenrut. People on add-ons mailing list maybe interested about this regarding the website. I'll send this there along links to related repos mrconfig and addon-store-submission, pointing out that it's a work in progress.
