### ISSUE TITLE
Fix the translations system for add-ons

### ISSUE THREAD

**Issue by nvdaes** [nvaccess/mrconfig#3]
Exbi server is sending notifications about mr commands or folders that cannot be created.
This should be fixed so people can manage translations for add-ons. Alternatively, request people to manage them independently without using a central system.
Thanks.

**Comment by feerrenrut** [comment]
@nvdaes Could you please give an example for me to look at (either email to me directly or comment here is fine).

**Comment by nvdaes** [comment]
Ok, after job. Just seeing your notification on movile, but I cannot look at emails at this moments, maybe in 2 hours or so, or in the evening.

**Comment by nvdaes** [comment]
@feerrenrut, I have forwarded you an email with an example (privately). Please let me know if you need more examples to fix this.
Thanks

**Comment by bdorer** [comment]
@nvdaes is there any proggress here? May you attach your private mail here?

**Comment by nvdaes** [comment]
Hi Bernd, I think this is fixed for most add-ons. Reef mentioned some add-ons that need to be managed by author to match the system requirements, but this is not an issue in the system itself:

https://nvda-addons.groups.io/g/nvda-addons/message/14955

Another question would be that documentation is needed to register new add-ons to be translated.
@feerrenrut , can you confirm if this is fixed? In this case, you may close this issue.
Should we create an issue requesting documentation about registering new add-ons to be translated? I would need this for pcKbBrl add-on, available on the community website and on my GitHub account, for example.
@grisov maybe also interested, according to a [public conversation](https://github.com/nvdaes/placeMarkers/pull/26).

My email address is: nrm1977@gmail.com
Cheers

**Comment by grisov** [comment]
Thank you Noelia!  

Yes, I am also interested in this question.  

For example, the [Quick Dictionary](https://addons.nvda-project.org/addons/quickDictionary.en.html) add-on is already published on the community website, but I don't know yet what steps I need to take to register this new add-on to be translated.  

It would be great if there was a simple step-by-step instruction.

**Comment by feerrenrut** [comment]
I think this issue should be resolved. I agree it would be good to have docs about how to add a new addon. Please create a new issue, with a link to the addon that should be introduced to the translations system. I'll have to learn all the details myself for introducing a new addon, as part of that I will document the process and requirements.
