### ISSUE TITLE
Register pcKbBrl add-on

### ISSUE THREAD

**Issue by nvdaes** [nvaccess/mrconfig#30]
Please, register this add-on to be translated with the translations system.

- url: https://github.com/nvdaes/pcKbBrl
The add-on is available on the official website. @feerrenrut , you will note that NV Access is an author of this add-on, but I'm maintaining it with agreement of @jcsteh 

Documentation about adding new add-ons to the old system, when I had access to NV Access server, is available at

https://github.com/nvdaaddons/nvdaaddons.github.io/wiki/MakeAddonsTranslatable

Thanks

**Comment by feerrenrut** [comment]
I have update the readme with these instructions: https://github.com/nvaccess/mrconfig/blob/master/readme.md

The first step is to get a clone of the addon here: https://github.com/nvdaaddons
When that is done I can register the addon.

**Comment by nvdaes** [comment]
Thanks. I'll share the instructions on the add-ons mailing list so that people request the registration there. I'll fork pcKbBrl soon and I'll inform you.

**Comment by nvdaes** [comment]
@feerrenrut and @nvaccess, I've forked the repo in nvdaaddons organization and created the stable branch. You can register the add-on in the server. Thanks.

**Comment by feerrenrut** [comment]
Completed via 353827b00e4a53fdbba4b0a8cf05e63caae4fd36 and 574c3dbb3d8e1df87a671e26ae01f5bfa2c3883a
