### ISSUE TITLE
Register Windows Magnifier in translation system

### ISSUE THREAD

**Issue by CyrilleB79** [nvaccess/mrconfig#35]
Could you please register Windows Magnifier in the translation system? This add-on is already present on the official add-on community website, for now in dev section; but I have requested the stable version to be downloadable in [this PR](https://github.com/nvaccess/addonFiles/pull/97)

GitHub repo URL:
https://github.com/CyrilleB79/winMag

The repo has already been [forked](https://github.com/nvdaaddons/winMag) by @nvdaaddons and I have pushed the stable branch there.

**Comment by feerrenrut** [comment]
This has been completed:
- 4ebe3ae7a1317dd629f14236042d70ab848a0dbc
- 8dc4319231de4e15480e39a325a2bba7d6f4fed2

**Comment by CyrilleB79** [comment]
Thanks @feerrenrut for the work already done for this, but the framework does not fully work: translation jobs are not received.

For example for French:
* The line regarding this add-on has been correctly added in the `fr/settings`.
* We have enabled the request to receive translation jobs for this add-on in `fr/settings`, i.e. the value 1 has been set in the following line
  `"addon.winMag": "1",`
* But the translation job has not been received, i.e. no `fr\add-ons\winMag` has been created

Could you please reopen this issue or fix it?

Thanks.

**Comment by CyrilleB79** [comment]
The first job of in the SRT repo has been received Friday evening.

However only the variables of the `buildVars.py` file have been translated, not the ones of the add-on. But running the `scons pot` locally on my side generates all the messages.

I guess it is due to a case issue in the path of the files to be translated. That would explain why it is working on my side (on Windows), but not in the translation framework, that runs `scons pot` under Linux I guess.

I will push an update with the corrected case in the path and check the result.

Note: I have hidden my previous message since I just had to wait the cron job on Friday evening. Do not take into accoutn.

**Comment by CyrilleB79** [comment]
Some updates after last Friday's evening synchronization:
* Now that I have fixed the case issue, all the translatable messages of this add-on have reached the SVN SRT repo.
* In the other direction however, the already translated messages from buildVars.py have not been merged in nvdaaddons/winMag repo; this issue that seems more global is tracked in #37 (cf. * In the other direction).
