### ISSUE TITLE
Synchronization issue for Outlook Extended, Windows Magnifier and maybe other add-ons

### ISSUE THREAD

**Issue by CyrilleB79** [nvaccess/mrconfig#37]
Hello

I have an issue regarding Outlook Extended add-on in the translation workflow.
The add-on is already part of the workflow for a long time. And SVN seems to be updated regularly when something is pushed in the stable branch of nvdaaddons/outlookExtended repo.

However, in the other direction, the work of translators in SVN is not merged back in the stable branch of nvdaaddons/outlookExtended repo.

A concrete example is the following commit:

```
Revision: 61945
Author: CyrilleB79
Date: vendredi 4 juin 2021 17:15:03
Message:
fr: Updated Outlook extended translation.
----
Modified : /fr/add-ons/outlookExtended/nvda.po
```

This SVN commit dates from the 4th of June but its content does not yet appear in the stable branch of nvdaaddons/outlookExtended.

The last commit coming from SVN in the stable branch of nvdaaddons/outlookExtended is the following:

```
commit 1ea892c0c734fde41f88abcb736adb54e501987a
Author: NVDA translation automation <nvda-translations@groups.io>
Date:   Fri May 14 15:06:08 2021 +0000
    l10n updates
```

**Comment by CyrilleB79** [comment]
The synchronization issue occurs also for Windows Magnifier add-on, recently added to translation system.
And probably for many, or maybe all, add-ons in the translation framework.

@feerrenrut do you plan to have a look at this soon? Just to know for planification.
If not, I will have to copy manually the individual translated .po files from SVN to the GitHub repo when making a new release including new translations. This would allow to have a partial update of translations, i.e. interface updated but documentation not.
Just let me know. Thanks.

**Comment by feerrenrut** [comment]
There were errors in the last translation run for this addon. It could be that this addon has been unlucky and not had a successful update in a while. There are so many add-ons and the system is fragile. The system is open, and I have tried to improve the documentation. For each case like this I have to look carefully at the state to understand what has happened and the appropriate way to fix it without introducing worse errors.

If you would like met to run the addon2svn or or svn2addon scripts for this addon again I can do that?

**Comment by CyrilleB79** [comment]
@feerrenrut I did not understand if you have fixed something or not.
If you have fixed something regarding Outlook Extended and Windows Magnifier, could you run svn2addon for them? I will then check in the result that everything goes well.
If you haven't fixed anything recently (i.e. after last Friday), there is still an issue. Maybe Windows Magnifier is easier to debug in a first time since addon2svn has not produced anything yet wherease new translations were already present in SVN repo befor last Friday.

If you need more details from my side (e.g. look for information in GitHub or SVN commit history), just let me know.

**Comment by feerrenrut** [comment]
I haven't done any investigation or changed anything yet. This can be quite time consuming and seems to be happening a lot. I'll check for and fix any obvious issues on the server now then run the addon2svn script.

**Comment by feerrenrut** [comment]
During that period the webhook was broken. Have you tried making another commit to the SRT repo?

**Comment by CyrilleB79** [comment]
Which period are you talking of exactly?
Also do you confirm me that svn2addon is scheduled once a week, every Friday?

**Comment by feerrenrut** [comment]
From the example given:
> 4 juin 2021 17:15:03

> Also do you confirm me that svn2addon is scheduled once a week, every Friday?

Yes, correct.

This week there was a svn lock error for 'outlook Extended'
I don't see any issues there right now. I'll run the script.

**Comment by feerrenrut** [comment]
I had to run it many times, but eventually it completed without errors. I believe the script has a race condition, it is more likely to fail when there are updates to many languages.

**Comment by CyrilleB79** [comment]
Outlook Extended seems OK now. Thanks.

Regarding Windows Magnifier:
Did you run the svn2addon script also for Windows Magnifier (winMag)? I cannot seen anything new in the stable branch of nvdaadon/winMag repo.
As a reminder, Windows Magnifier has been recently added to the translation framework and svn2addon has never worked successfully on this add-on.

**Comment by feerrenrut** [comment]
I'm working through the addon's that had errors last Friday. I'm doing winMag now.

**Comment by CyrilleB79** [comment]
> I'm working through the addon's that had errors last Friday. I'm doing winMag now.

OK no problem. Many thanks.

**Comment by feerrenrut** [comment]
I'm closing this issue, it appears to be resolved.

**Comment by CyrilleB79** [comment]
Hi Reef

Thanks for the work already done. Outlook Extended seems to be OK (interface and doc have been updatedd).

Unfortunately a problem remains with Windows Magnifier:
The interface seems to have been updated corectly: 4 .po files have been added in the `locale` folder. But no documentation file has been included in the add-on, although many pages of the website have already been translated (e.g. French one).

Can you have a look again?
Thanks.

**Comment by feerrenrut** [comment]
Could you please point me to these files.

**Comment by feerrenrut** [comment]
The po files in the locale are fine. Please tell me the location of the translated documentation files, and where you expect them to end up.

**Comment by CyrilleB79** [comment]
Here is an example:

The source file is the following:
`SRT/website/addons/windowsMagnifier.fr.po`
This file has some translated messages (actually 100% translated).
The last commit was done before the last run of svn2addon. It is the following:
```
Revision: 62597
Author: CyrilleB79
Date: mercredi 30 juin 2021 15:05:11
Message:
website: fr - Windows Magnifier: Update translation (link)
----
Modified : /website/addons/windowsMagnifier.fr.po
```

The destination file should be the following in the addonFile/winMag GitHub repo:
`addon/doc/fr/readme.md`

HTH

**Comment by feerrenrut** [comment]
elsewhere the addon name is `winMag` why are these files called `windowsMagnifier.fr.po`?

**Comment by feerrenrut** [comment]
Looking at the script, that seems likely to be the problem: https://github.com/nvaccess/mrconfig/blob/master/.sh.d/01_svn2addon.sh#L50

**Comment by feerrenrut** [comment]
Was that file created by a human, or the system?

**Comment by CyrilleB79** [comment]
The file `windowsMagnifier.fr.po` is created or updated automatically each time `windowsMagnifier.mdwn` is updated.
The file `windowsMagnifier.mdwn` has been created manually (and is updated manually). The creation commit is the following:
```
Revision: 54839
Author: nvdakor
Date: mardi 18 février 2020 17:34:02
Message:
add-ons - add Windows Magnifier.
----
Added : /website/addons/windowsMagnifier.mdwn
```

I guess it is just a mistake. Cc @josephsl (who created it) and @nvdaes (who was also involved in translation system) for confirmation.

Note that some add-ons that already belong to the translation system have a different name between SRT website page file names and nvdaaddons repo name. However these are only case difference. And I guess that it is not a problem (at least for feching the repo). Examples:
* eMule.fr.po / emule
* sentenceNav.fr.po / SentenceNav

Also beware that pcKbBrl integration (requested in #30) may have the same issue in the future. Indeed, the webpage file name is `pcKeyboardBrailleInput.fr.po` whereas the original repo is nvdaes/[pcKbBrl](https://github.com/nvdaes/pcKbBrl)

Also, among others these one may present the same issue if integration in the framework is requested in the future:
* nvda-speech-history / speech_history.fr.po (author @jscholes)
* updateChannel / updateChannelSelector.fr.po (author @nvda-es with the hyphen = not Noelia)

**Comment by nvdaes** [comment]
Thanks Cyrille, though now I cannot confirm issues about the system as
done previously, when I received notifications from the server and had
access to it.

Have a good day,

Noelia
Cheers,


2021-07-07 16:20 GMT+02:00, Cyrille Bougot ***@***.***>:

**Comment by feerrenrut** [comment]
Ok. It seems very likely this is the issue. @CyrilleB79 will you be able to adjust that page / translation name?

**Comment by CyrilleB79** [comment]
Yes, I will take care of it.
I let you know when it is done.

**Comment by CyrilleB79** [comment]
This is done. Any previous direct link to the add-on's page is not valid anymore.
But the internal links on the website are OK.

@feerrenrut you may want to run svn2addon again to check. Or I will wait the automatical run at the end of this week (Friday evening).
In any case, I'll let you know the result.

**Comment by feerrenrut** [comment]
Looks like that was successful, stable branch has been updated:
https://github.com/nvdaaddons/winMag/commit/d6c8a5a4a4cb75ea6a40a440be4f3c089d3b2fda

**Comment by nvdaes** [comment]
Then I'll look at eMule and pcKbBrl .mdwn in case this may cause
issues, and rename then according to the repo.

2021-07-08 12:12 GMT+02:00, Reef Turner ***@***.***>:

**Comment by CyrilleB79** [comment]
@feerrenrut wrote:
> Looks like that was successful, stable branch has been updated:

Yes confirmed. This issue is resolved. Many thanks Reef for all the investigations and the fixes!

@nvdaes wrote:
> Then I'll look at eMule and pcKbBrl .mdwn in case this may cause issues, and rename then according to the repo.

Yes for pcKbBrl.
For eMule, it is just a case issue and it does not seem to be problematic. Just keep it in mind if you see issues in the translation for this ad-on in the future.

**Comment by nvdaes** [comment]
Ok Cyrille (from mobile)
