### ISSUE TITLE
Last commits in SRT are not shown on the website

### ISSUE THREAD

**Issue by CyrilleB79** [nvaccess/mrconfig#39]
Since yesterday at least, new commits in the SRT repo do not trigger the corresponding update on the add-on community website.

Here is a precise example for Access8Math add-on documentation on the website:

The last SRT commit for the French translation of this documentation is:
```
Revision: 62371
Author: michelsuch
Date: mercredi 23 juin 2021 11:24:39
Message:
fr - website - addons/access8math.fr.po - access8math updated
----
Modified : /website/addons/access8math.fr.po
```

Making an SVN diff on this commit with the previous wone, we can clearly see that the initial description of the add-on (after download link / compatibility statement) has been translated in French.

However, on the website, the initial description (among other) is still in English. Here is the French page:
https://addons.nvda-project.org/addons/access8math.fr.html

There are other pages (if not all) that have not been updated recently on the website.

Cc @michelsuch who is the person who has updated specifically this documentation.

**Comment by jmdaweb** [comment]
Hi,
In case it's related to this issue, po files stopped being updated just after I fixed some Markdown errors in Access8math documentation. I may revert the commit and see what happens.

**Comment by CyrilleB79** [comment]
@jmdaweb, please do not revert before you have ensured your commit is faulty.

Actually, the following commit seems to have triggered correctly an update on the website and is posterior to your commit:
```
Revision: 62370
Author: ivnc
Date: mercredi 23 juin 2021 11:03:46
Message:
GL: website/addons/placeMarkers&winWizard 100%
----
Modified : /website/addons/placeMarkers.gl.po
Modified : /website/addons/winWizard.gl.po
```

On the contrary, the first failing commit is:
```
Revision: 62371
Author: michelsuch
Date: mercredi 23 juin 2021 11:24:39
Message:
fr - website - addons/access8math.fr.po - access8math updated
----
Modified : /website/addons/access8math.fr.po

```

**Comment by feerrenrut** [comment]
This was caused by conflicts within ikiwiki's SVN working directory on the server for the `/website/addons/access8math.fr.po` file.
The page for this addon appears to be up to date now: https://addons.nvda-project.org/addons/access8math.fr.html

I don't know what caused the conflicts.

Information for NV Access in case this happens again.
To restore I used
- `svn cleanup' 
- 'svn update'
- 'svn revert --recursive .`
- then ran the post commit command again. `~/ikiwiki/publish/post-commit`

**Comment by CyrilleB79** [comment]
Yes the page seems OK now. Thanks!

For my information, in such cases:
* Is there a way for us (translators) to see that there is this conflict
* is there anything we can do on our side or do you need to make an intervention to fix the conflict?
Thanks.

**Comment by feerrenrut** [comment]
No unfortunately not. This was difficult to determine the cause and took me quite a lot of time to find. I'd like to make this situation more easy to discover but without knowing what action caused it makes it difficult.

**Comment by jmdaweb** [comment]
Hi,
After updating Access8Math.mdwn, I can confirm that po files update is not triggered for this document. I updated it in order to fix some formatting issues before updating the spanish translation.

**Comment by CyrilleB79** [comment]
@jmdaweb just a question:
Are you in contact of the author of Access8Math?
If not, I recommend you to put him in the loop. Else, the issues you are fixing in the doc will turn back when the add-on is updated.

**Comment by CyrilleB79** [comment]
@feerrenrut, @jmdaweb:
The update of the website content is broken again.
Please look at `windowsMagnifier.mdwn`'s history. Especially:

1. The website English content does not match the last commit of `windowsMagnifier.mdwn`:
```
Revision: 62532
Author: CyrilleB79
Date: lundi 28 juin 2021 17:29:22
Message:
website: Windows Magnifier - Reverted last .mdwn modification since it causes issue with bullet list not split correctly. Sorry translators.
----
Modified : /website/addons/windowsMagnifier.mdwn
```

2. The CommitBot has not generated any .po file following this revision.

May this issue due to too near updates?

**Comment by feerrenrut** [comment]
Looking at `addons/windowsMagnifier.de.po` there is the following conflict. I'm going to try to track down where each of the revisions come from.
```
<<<<<<< .mine
"Ansage ein- oder ausschalten: Wenn diese Option aktiviert ist, wird der "
"Status der Lupe gemeldet, wenn Sie Windows+Plus or Minus oder Windows+Escape "
"verwenden, um sie ein- oder auszuschalten."
||||||| .r62535
=======
"Diese Option betrifft nur den Vollbild_modus.\n"
"* Melden aktivieren oder deaktivieren:\n"
"  Wenn diese Option aktiviert ist, wird der Status der Lupe gemeldet, wenn Sie Windows++- oder Windows+Escape-Befehle verwenden, um sie ein- oder auszuschalten.\n"
"* Zoom-Faktor ansagen:\n"
"  Wenn diese Option aktiviert ist, wird der Zoom-Faktor der Lupe angesagt, wenn Sie Windows+Plus oder Windows+Minus verwenden.\n"
"* Invertierte Farben ansagen:\n"
"  Wenn diese Option aktiviert ist, wird der Status für die invertierte Farbe angesagt, wenn Sie den Befehl Strg+Alt+I verwenden.\n"
"* Ansichtsänderung ansagen:\n"
"  Wenn aktiviert, wird der Ansichtstyp ansagen, wenn Sie einen Befehl verwenden, der den Ansichtstyp ändert (Strg+Alt+M, Strg+Alt+F, Strg+Alt+D, Strg+Alt+L)\n"
"* Größenänderung des Objektivs oder des angedockten Fensters ansagen:\n"
"  Wenn diese Option aktiviert ist, wird eine Meldung ausgegeben, wenn Sie die Befehle für die Größenänderungen verwenden (Alt+Umschalt+Pfeiltasten).\n"
"  Im angedockten Fenstermodus wird die Höhe oder Breite angesagt.\n"
"  Im Objektivmodus kann die neue Dimension vorerst nicht angesagt werden.\n"
"  Diese Größenänderungsbefehle scheinen nicht in allen Windows-Versionen verfügbar zu sein; Wenn Ihre Windows-Version sie nicht unterstützt, sollten Sie diese Option deaktiviert lassen.\n"
"* Übergeben Sie in Dokumenten und Listenansichten die Tastenkombinationen Strg+Alt+Pfeiltasten an die Windows-Lupe:\n"
"  Es gibt drei Möglichkeiten:\n"
>>>>>>> .r62536
```

**Comment by jmdaweb** [comment]
@CyrilleB79 no, I haven't contacted this author. I usually fix Markdown format directly in srt and repeat whenever the document is updated and breaks. It's easier than contacting each author, since only @josephsl and a few others format their Markdown correctly for the translation system. It might be a good idea writing a post in both nvda-translations and nvda-addons lists, and eventually publishing it as a document on the nvda-addons organization or the NVDA wiki. However, even doing these things, I'm sure most authors would keep the bad format since GitHub displays the documents properly.

**Comment by CyrilleB79** [comment]
@jmdaweb, if you want to write something in the wiki, I would be very interested and probably other people. Just for Windows Magnifier documentation, I have had issues yesterday regarding:
* lists and sublists
* long links
Having this information in the wiki would have saved me from making various tests on the winMag doc yesterday.

When you have something in the wiki, you can communicate on the lists to inform people and to have it reviewed/appended if needed.
I agree that probably not all add-on authors will take it into account directly. However sending them an e-mail with the modified readme from SVN may encourage them to update the readme of their repo.

**Comment by feerrenrut** [comment]
The website should be up to date again. The issues hasn't been determined, but we have made it easier to get more information. Please let us know if it happens again.

**Comment by jmdaweb** [comment]
Thanks Reef.

**Comment by CyrilleB79** [comment]
Thank you. It seems to work correctly.
