### ISSUE TITLE
Register directLink add-on in translation system

### ISSUE THREAD

**Issue by nvdaes** [nvaccess/mrconfig#40]
I'll forked the repo in nvdaaddons organization and checked that it contains a stable branch to request the registration, according to a conversation with @fawazar94 in PR 110 of addonFiles, ready to be reviewed by @feerrenrut after my approval.
Thanks

**Comment by feerrenrut** [comment]
This has been completed.

**Comment by feerrenrut** [comment]
@nvdaes Could you confirm that GitHub user @nvaccessAuto has write access to the directLink repository? Currently the translation update is failing with 
```
ERROR: Permission to nvdaaddons/DirectLink.git denied to nvaccessAuto. fatal: Could not read from remote repository.
```

**Comment by nvdaes** [comment]
I have granted access to @nvaccessAuto right now. Previously it wasn't granted.

**Comment by feerrenrut** [comment]
Thanks, this now seems to be working.
