### ISSUE TITLE
Create issue template to request add-ons registration

### ISSUE THREAD

**Issue by nvdaes** [nvaccess/mrconfig#41]
This may make easy to request add-ons registration, which can be a repeatitive process and requires standardized fields.
Issue forms (for now in beta stage) maybe easier that the markdown template.
I have created a sample for testing on my .github repo, used to store issue templates and other guidelines for all my projects on GitHub by default. Let me know if I should create a PR.

- [Template for testing](https://github.com/nvdaes/.github/blob/master/.github/ISSUE_TEMPLATE/registerAddon.yml). I'll remove it when this issue is resolved
- [Issue templates, included forms](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/configuring-issue-templates-for-your-repository)
cc: @CyrilleB79

**Comment by CyrilleB79** [comment]
You may want to include a 'Additional comments' field.
For example, look at PR #32: I have found useful to say explicitely that there are other localized files than the standard ones that do  not need to be taken into account in the automatic translation framework.

**Comment by nvdaes** [comment]
Adding a textarea for additional comments maybe useful.
Though, regarding your comment aboutfiles that shouldn't be localized, I'm not sure if this can be addressed in this repo. I think that, if possible, you should define them avoiding its inclusion in local sources via addonTemplate.
🤔

My template is just a test, so I won't modify it unless I should create a PR.

**Comment by CyrilleB79** [comment]
> Though, regarding your comment aboutfiles that shouldn't be localized, I'm not sure if this can be addressed in this repo. I think that, if possible, you should define them avoiding its inclusion in local sources via addonTemplate.
> 🤔

I was referring to the following comment in #32:
> Note: The translation of localized files specific to this add-on (found in addon/globalPlugins/charinfo/locale/xx) should not be localized via this automatic translation framework. Instead, localization of these files should be done directly via PR's in the charInfo add-on's repo or contacting the add-on author (me).

IMO there is no risk to interfer with translation system. Indeed, the files in addon/globalPlugins/charinfo/locale/xx are only text files. Thus they are not impacted by gettext and Python files.
I was just mentioning them since they are files located in language folders.

Anyway, if there is something still unclear on this point or if I have missed something, let's rather comment further in #32.

**Comment by feerrenrut** [comment]
Yep, I'm fine with this @nvdaes. Feel free to open a PR. Do note that now the release is out, we are actively working on the add-on store, and making plans to replace the translation system. I'll mention you when the translation system plans become available.

**Comment by feerrenrut** [comment]
I meant to say "now the release is almost out".

**Comment by nvdaes** [comment]
OK @feerrenrut. I'm working in my fork of addonFiles to send the template there.

2021-07-06 7:32 GMT+02:00, Reef Turner ***@***.***>:

**Comment by feerrenrut** [comment]
This was completed with #46
