### ISSUE TITLE
[Register add-on in translation system]: easyTableNavigator

### ISSUE THREAD

**Issue by feerrenrut** [nvaccess/mrconfig#49]
### Add-on name

easyTableNavigator

### Add-on maintainer

@josephsl

### Stable branch

- [X] Stable branch exists in add-on repo

**Comment by josephsl** [comment]
HI, and I hereby give permission to let NV Access maintain a copy of l10n data for this add-on (although I don’t maintain this add-on anymore, as the original creator, I give you my blessing). Thanks.

**Comment by feerrenrut** [comment]
Completed.
