### ISSUE TITLE
Translation files for WinWizard not present in the SVN

### ISSUE THREAD

**Issue by lukaszgo1** [nvaccess/mrconfig#51]
In #48 I've asked for WinWizard to be included in the translations system. While the issue has been closed as fixed  no *.po files appear for translators in the SVN even for languages for which translations for WinWizard are enabled. Originally reported by @cary-rowen  cc @feerrenrut Would you be able to look into this?

**Comment by feerrenrut** [comment]
The issue has been found and addressed. This should be resolved.

**Comment by cary-rowen** [comment]
Yes, this has been resolved.
