### ISSUE TITLE
[Register add-on in translation system]: systrayList

### ISSUE THREAD

**Issue by ruifontes** [nvaccess/mrconfig#52]
### Add-on name

systrayList

### Add-on maintainer

@ruifontes

### Stable branch

- [X] Stable branch exists in add-on repo

**Comment by feerrenrut** [comment]
systrayList is already translatable via the system.

For instance it is enabled for Spanish translators:
https://app.assembla.com/spaces/screenReaderTranslations/subversion/source/HEAD/es/settings/#ln48

The final steps require merging from nvdaaddons/systrayList 'stable' branch. For detailed instructions see https://github.com/nvaccess/mrconfig#maintaining-the-add-on

I'll close this issue.
