### ISSUE TITLE
[Register add-on in translation system]: access8Math

### ISSUE THREAD

**Issue by nvdaes** [nvaccess/mrconfig#58]
### Add-on name

Access8Math

### Add-on maintainer

@tsengwoody

### Stable branch

- [X] Stable branch exists in add-on repo

**Comment by nvdaes** [comment]
@tsengwoody, GitHub Actions cannot build the .pot file and scons is terminated. Check the actions link to see tha workflow failure corresponding to this issue. Maybe you have a non ascii character? Unless @feerrenrut says a different thing, you should fix this before this add-on can be included in the translations system.
Also, usually add-on names start in lowercase, but I think that this will not affect the result of the registration.
Thanks

**Comment by CyrilleB79** [comment]
Yes, `A8M_PM.py` has a BOM at the beginning.
The file should be formatted in UTF8 without BOM (due to gettext limitation if I remember well).

**Comment by tsengwoody** [comment]
I update my repository to fixed A8M_PM.py bom character and use gettext to translate about message.
Do I need do any another step?

**Comment by nvdaes** [comment]
Lets close and reopen to see if GitHub Actions can build the add-on now.

**Comment by nvdaes** [comment]
This is not working for now. I suggest you:

- See section encoding of the [contributing to NVDA document](https://github.com/nvaccess/nvda/wiki/Contributing)
- - You may want to use a GitHub workflow created by @mhameed, first creator of the current translation system used by NVDA and add-ons, contributor to add-ons and to the add-on template among other things. This GitHub workflow created by him checks if Python files contain BOM characters. He helped me to practice GitHub Actions too. You may find the mentioned workflow (.yaml file) in add-ons like [clipContentsDesigner](https://github.com/nvdaes/clipContentsDesigner)

**Comment by CyrilleB79** [comment]
@tsengwoody, you have updated the stable branch in your repo, but you need to push it to the nvdaaddons fork of your repo (https://github.com/nvdaaddons/Access8Math.git).
The translation framework looks and interact with this fork, not your personal repo so you need to synchronize them.

**Comment by tsengwoody** [comment]
I seem to have`t write permission
git push got error
fatal: unable to access 'https://github.com/nvdaaddons/Access8Math/': The requested URL returned error: 403
or how to synchronize?

**Comment by nvdaes** [comment]
Thanks Cyrille and Woody. @tsengwoody, I've just invited you to the
repo in nvdaaddons organization. Please accept the invitation and push
to stable branch.

2021-09-08 9:19 GMT+02:00, Tseng Woody ***@***.***>:

**Comment by tsengwoody** [comment]
I updated nvdaaddons repo please try again

**Comment by nvdaes** [comment]
Thanks. All is right now, ready to be included in the translations system when @feerrenrut  can do it.

**Comment by feerrenrut** [comment]
This should now be available for translation.
