### ISSUE TITLE
[Register add-on in translation system]: Update Channel Selector

### ISSUE THREAD

**Issue by jmdaweb** [nvaccess/mrconfig#61]
### Add-on name

updateChannel

### Add-on maintainer

@jmdaweb

### Stable branch

- [X] Stable branch exists in add-on repo

**Comment by jmdaweb** [comment]
Link to the thread requesting registration in the translation system: https://nvda-addons.groups.io/g/nvda-addons/message/17407
Note that the repos haven't been forked to NVDAAddons organization yet.

**Comment by feerrenrut** [comment]
updateChannel should now be available for translators.
