### ISSUE TITLE
[Register add-on in translation system]: Proxy support

### ISSUE THREAD

**Issue by jmdaweb** [nvaccess/mrconfig#62]
### Add-on name

proxy

### Add-on maintainer

@jmdaweb

### Stable branch

- [X] Stable branch exists in add-on repo

**Comment by jmdaweb** [comment]
@nvdaes, can the fork be renamed from nvda-proxy-support to proxy? I know @feerrenrut can fix manually this problem, but that might be a better solution.
Thanks.

**Comment by nvdaes** [comment]
I"ve renamed the repo now.

**Comment by feerrenrut** [comment]
proxy should now be available for translators.
