### ISSUE TITLE
Access8Math translations are not updated in nvdaaddons repo

### ISSUE THREAD

**Issue by CyrilleB79** [nvaccess/mrconfig#64]
In the [nvdaaddons/Access8Math](https://github.com/nvdaaddons/Access8Math) repo, the last commit of the stable branch is:

```
commit d4562e9b5fbee671a2b250b2687fae587c8acbdb (tag: v3.1)
Author: Tseng Woody <tsengwoody.tw@gmail.com>
Date:   Tue Sep 21 17:38:24 2021 +0800

    *       In the general settings, user can select Math Player as the speech/braille/interact source only if user`s system have Math Player installed.
```

However, on SVN SRT repo, there are more recent translations, e.g.:
```
Revision: 65209
Author: CyrilleB79
Date: mardi 9 novembre 2021 12:14:32
Message:
fr: Access8Math interface - Translation finished; some checks still to be done.

----
Modified : /fr/add-ons/Access8Math/nvda.po
```

The stable branch should have been updated with new translations (usually every week).

@feerrenrut could you have a look at it?

Cc @tsengwoody, author of the add-on.

**Comment by CyrilleB79** [comment]
Nothing to do with Access8Math translation, but:
For information, a GitHub action has been triggered on this issue and I have received an e-mail message with the following indication:
"Check stable branch: All jobs have failed"

These checks only make sense if the issue regards a new add-on inclusion in the translation framework.
@feerrenrut, @nvdaes is there a way to trigger it only when the template to add a new add-on is used?

**Comment by nvdaes** [comment]
Hi Cyrille, I think this is possible using paths in the workflow. I'll
look all the next weekend.

2021-11-17 11:39 GMT+01:00, Cyrille Bougot ***@***.***>:

**Comment by feerrenrut** [comment]
There were paths in comments in the po file. These shouldn't end up in there. They are supposed to be removed via the filter in the `.gitattributes` file. I removed them, see commit: https://github.com/nvdaaddons/Access8Math/commit/c1b85f693d0a1362014d07e6b0fa2dc4b13d368e

**Comment by CyrilleB79** [comment]
Thanks for the very quick fix!
