### ISSUE TITLE
Notifications from SRT repo not received anymore

### ISSUE THREAD

**Issue by CyrilleB79** [nvaccess/mrconfig#69]
I do not receive any notification regarding activities on the screenreadertranslations repo anymore.
This has been so for 3-4 weeks.

I have [asked](https://groups.io/g/nvda-translations/topic/88100515#2822) on the translators mailing list and the issue seems the same for at least another person.

I used to receive notifications for modifications in the 'fr' folder (French) as well as in the 'website' folder.

@feerrenrut, could you have a look at it?
Many thanks!

**Comment by feerrenrut** [comment]
Sorry it took a while to come to this, can you confirm this issue is still ongoing? I seem to have recent emails about translation activity.

**Comment by CyrilleB79** [comment]
Hello

Thanks for taking care of this issue.

Yes, the issue is still present on my side. I think that I have not received any notification from SRT repo since the beginning of the year (2022). I have subscribed to 'fr' and 'website' notifications.

I have sent an e-mail in [this thread](https://groups.io/g/nvda-translations/topic/88100515?p=Created,,,100,1,0,0::recentpostdate/sticky,,,100,2,0,88100515,previd=1642246261300917022,nextid=1622471650527247851) of the translation mailing-list to ask for feedback from the other people.

**Comment by cary-rowen** [comment]
Hi,
I almost never get a notification.
Thanks

**Comment by feerrenrut** [comment]
Translators expect to get an email when changes are made to files for any languages their email address is registered for. The registration is file:
[mrconfig/addressData.py at master · nvaccess/mrconfig (github.com)](https://github.com/nvaccess/mrconfig/blob/master/scripts/addressData.py)

I'm going to close this for now, please re-open if there are any new issues. There are several known issues with the current system that I'll outline here:
- We are no longer receiving (from assembla via webhook) the complete list of files changed. This means that email notifications are not sent to some translators for commits that affect many languages (E.G. a new merge from master to beta). Currently only language code before 'ta' (alphabetically) will get notifications.
- Some email providers block / filter these email as spam, to resolve this please contact your email provider.
