### ISSUE TITLE
SRT repo has become large

### ISSUE THREAD

**Issue by feerrenrut** [nvaccess/mrconfig#7]
The SRT repo has become very large. Checkouts / updates take a long time, converting to Git (and retaining commits) would take days if done on my machine (I assume GitHub could do this import much faster).

There are many transient files, such as the diffs for t2t files that seem to build up.

**Comment by dpy013** [comment]
The current repository import function of NVDA's svn repository github is no longer able to import properly:
We found an error during import
We recommend restarting the import process, but if you are still having trouble
[contact support](https://github.com/contact)
This repository is too large.

**Comment by bdorer** [comment]
If NVDA 2021.1 translation has been completed I'll update translation wiki and will remove old diffs. Translations which aren't updated should be deleted in my point of view.

**Comment by dpy013** [comment]
> If NVDA 2021.1 translation has been completed I'll update translation wiki and will remove old diffs. Translations which aren't updated should be deleted in my point of view.

I agree with your comment

**Comment by dpy013** [comment]
Also I personally think that the conversion process of translation repositories needs to be speeded up, currently svn has a lot of problems.
The first problem is the huge size, the second problem is that there are some localization maintainers who cannot receive emails, and the last problem is that the translation repository cannot effectively collaborate with the main codebase effectively and has to use two sets of version management tools.
thanks.

**Comment by dpy013** [comment]
Hello everyone
I have used a day
I converted the screenReaderTranslations svn repository to git on my Tencent cloud server.
Note: This is a preliminary conversion, there may be a lot more work to be done.
Here is the github repository address:
https://github.com/xingkong0113/NVDA-IE8n.git
thanks

**Comment by feerrenrut** [comment]
That is interesting @xingkong0113, can you tell us how big that repository is?

**Comment by feerrenrut** [comment]
We plan to abandon the mrconfig based approach, overview of new approach: https://github.com/nvaccess/translationSystem

This will involve moving the contents of SRT to GitHub.

**Comment by bdorer** [comment]
I removed 1 gb of data.a, 5865 files. There are more than 2200 not translated po files wich I could remove if desired.
