### ISSUE TITLE
[Register add-on in translation system]: cursorLocator

### ISSUE THREAD

**Issue by nvdaes** [nvaccess/mrconfig#77]
### Add-on name

cursorLocator

### Add-on maintainer

@nvdaes

### Stable branch

- [X] Stable branch exists in add-on repo

**Comment by nvdaes** [comment]
Ping @feerrenrut.
Can you register this in the translation system?
cc: @sergiogomez31, coauthor of the add-on.

**Comment by seanbudd** [comment]
Apologies for the late actioning.
This should now be registered.

**Comment by seanbudd** [comment]
Apologies, it looks like `automatic.crontab` was given the wrong reference, so this was not correctly registered.

This should be fixed as of https://github.com/nvaccess/mrconfig/commit/8c26149c4d78637e06128ae050d0969fe5d3aaec
