### ISSUE TITLE
[Register add-on in translation system]: enhancedAnnotations

### ISSUE THREAD

**Issue by nvdaes** [nvaccess/mrconfig#79]
### Add-on name

enhancedAnnotations

### Add-on maintainer

nvdaes

### Stable branch

- [X] Stable branch exists in add-on repo

**Comment by nvdaes** [comment]
cc: @GeorcheKerscher @ruifontes

**Comment by seanbudd** [comment]
Apologies for the late actioning.
This should now be registered.
