### ISSUE TITLE
Use pot or xliff format for userguide

### ISSUE THREAD

**Issue by feerrenrut** [nvaccess/mrconfig#8]
For the user guide and other long form content translators are expected to maintain a translated version of the file, keeping the structure compatible and using diff files to guide where changes must be made.

Instead, if we can adjust the system to use pot or xliff format for the userguide, then translators can work entirely withing poedit.

This will likely help to improve the repository size issue (#7) going forward.

**Comment by bdorer** [comment]
This would be great but before NVDA'S Poedit support must be revisited. At the moment translators have no chance to see which line is translated or fuzzy without checking translation or the coresponding checkbox.

**Comment by feerrenrut** [comment]
Thanks for that comment @bdorer. Could you please create an issue on NVDA, it is really an issue with NVDA.

**Comment by bdorer** [comment]
thanks @feerrenrut. There are allready issues such: #7303, #4371, #11044.

**Comment by feerrenrut** [comment]
We plan to abandon the mrconfig based approach, overview of new approach: https://github.com/nvaccess/translationSystem

This will include transitioning to a new approach for t2t files.
