### ISSUE TITLE
Issue with Turkish translation

### ISSUE THREAD

**Issue by CyrilleB79** [nvaccess/mrconfig#81]
@feerrenrut, @seanbudd, could you please have a look at this issue before the end of translation freeze?

### Context
Issue reported by Turkish translator in [this thread](https://groups.io/g/nvda-translations/topic/an_issue_with_turkish/93569115?p=,,,100,0,0,0::recentpostdate/sticky,,,100,2,0,93569115,previd%3D1662718078956949352,nextid%3D1631259669292295884&previd=1662718078956949352&nextid=1631259669292295884).

### Issue
Turkish nvda.po file does not seem to be updated in SVN to NVDA direction.

In SVN repo, tr\nvda.po has been fully translated in Turkish (2667 / 2667 messages translated) since the following revision:
```
Revision: 69532
Author: umutkorkmaz
Date: samedi 27 août 2022 14:07:55
Message:
TR: Updated.nvda.po. Added Three new strings translated.
```

However, in NVDA's beta branch, the last commit for `source\locale\tr\LC_MESSAGES\nvda.po` is:
```
commit b3410e60f87b6db586c92676aa8fd283f63f4375
Author: NVDA translation automation <nvda-translations@groups.io>
Date:   Fri May 6 00:01:56 2022 +0000
    L10n updates for: tr
    From translation svn revision: 67469
```

**Comment by feerrenrut** [comment]
Error sent out by translation system in response to that revision:
```
umutkorkmaz committed Changeset [69532]: TR: Updated.nvda.po. Added Three new strings translated.

TR: Updated.nvda.po. Added Three new strings translated.

Files Affected:
M /tr/nvda.po

Files count: 1
Commit (by umutkorkmaz)


File /home/nvdal10n/mr/srt/tr/nvda.po: 1 error

Message starting on line 7336
Original: "%s rem"
Translated: "% s kalan"
Error: unnamed percent interpolations differ
Expected: unnamed percent interpolations in this order: %s
Got: no interpolations
```

**Comment by seanbudd** [comment]
Closing as per resolution in the mailing list thread, the fix has been pushed by translators
