### ISSUE TITLE
[Register add-on in translation system]: speechLogger

### ISSUE THREAD

**Issue by XLTechie** [nvaccess/mrconfig#85]
### Add-on name

speechLogger

### Add-on maintainer

@XLTechie (but owned by @opensourcesys)

### Stable branch

- [X] Stable branch exists in add-on repo

**Comment by seanbudd** [comment]
This has been done, thanks for waiting

**Comment by XLTechie** [comment]
> This has been done, thanks for waiting

Thanks @seanbudd (also for #84)
