### ISSUE TITLE
[Register add-on in translation system]: nvdaRd

### ISSUE THREAD

**Issue by nvdaes** [nvaccess/mrconfig#86]
### Add-on name

nvdaRd

### Add-on maintainer

@leonardder

### Stable branch

- [X] Stable branch exists in add-on repo

**Comment by nvdaes** [comment]
@seanbudd The GitHub workflow for this needs to be updated. It's quite old and now, to create a comment for an issue, we need to address this change:

> github.issues.createComment in V4 becomes github.rest.issues.createComment in V5
Please see [GitHub Script readme](https://github.com/actions/github-script)

When this is done, we can close and reopen this issue so that the comment reflecting that this is ready for registration is added.

**Comment by seanbudd** [comment]
This add-on has now been registered

**Comment by LeonarddeR** [comment]
Thanks @seanbudd
