### ISSUE TITLE
[Register add-on in translation system]: TeleNVDA

### ISSUE THREAD

**Issue by nvdaes** [nvaccess/mrconfig#89]
### Add-on name

TeleNVDA

### Add-on maintainer

@jmdaweb

### Stable branch

- [X] Stable branch exists in add-on repo

**Comment by nvdaes** [comment]
Hi, GithUb Actions are failing. I can run scons locally, but here there's an error. Also, RD add-on could be registered properly and check passed. So this may contain amodified version of addonTemplate or something, and I don't know if this would be properly recognized when the addon is registered. Maybe, but then multiple version of the template would needto be addressed to run GitHub Actions, and I don't know if this can be done or how.
cc: @seanbudd

**Comment by jmdaweb** [comment]
Hi,
Note that this add-on needs Visual Studio to build an executable. The sconstruct file is slightly modified, but is almost identical to the one available on the add-on template. Are the actions based on another image without vs?
Regards.

**Comment by jmdaweb** [comment]
Confirmed. The action tries to use g++, and fails because windows.h is not available: https://github.com/nvaccess/mrconfig/actions/runs/4557071601/jobs/8038235472#step:6:43

**Comment by nvdaes** [comment]
The job is run on ubuntu-latest. I chose it when created the workflow
since I thought it would be the best option and I think that pot files
are created on ubuntu servers.
Here's related info:

https://github.com/actions/runner-images/blob/main/images/linux/Ubuntu2204-Readme.md

I don't have access to NV Access servers long time ago, so I don't
know what should be changed for GitHub Actions.

2023-03-29 21:35 GMT+02:00, José Manuel Delicado ***@***.***>:

**Comment by jmdaweb** [comment]
I also prefer any Linux variant rather than Windows on server environments. Ubuntu is a good choice to build most add-ons. However, TeleNVDA, NVDA Remote and other add-ons that need building executables from source require Windows, or a cross compiler on Linux, such as the MinGW toolchain. I see three possible solutions to this problem:

* Extend the Ubuntu image as part of the setup process, installing the MinGW toolchain and modifying the required environment variables.
* Switch to Windows with Visual Studio. I use it to build the add-on on the repo workflow without problems.
* Modify the sconstruct file to ignore errors if compilation of url_handler fails, replacing the fatal error with a warning. I will study this choice.

Regards.

**Comment by seanbudd** [comment]
Apologies for the difficulties.
To me, it seems like it makes the most sense to switch the workflow to Windows.
Do many add-on developers develop on linux?
Since NVDA is a Windows app it makes more sense to me that we build with Windows on this repo.

**Comment by nvdaes** [comment]
The workflow was created to test that processes can be correctly run on NV Access server. I dealed with lots of issues trying to register add-ons there, and my idea is that sometimes pot files weren"t created due to different approaches of add-on developers. I think that scons was used on the server, so my intention is to perform some previous tests before running registration commands on the Linux server used by NV Access.Previously some members of the community were in charge of add-ons registration on the server, but if the environment there is changed or you are sure that we can switch the workflow to Windows, I may create a PR if you want, using curl to download gettext exe files from nvda/miscDeps, used by scons to create gettext files on Windows.Enviado desde mi iPhoneEl 30 mar 2023, a las 3:44, Sean Budd ***@***.***> escribió:﻿
Apologies for the difficulties.
To me, it seems like it makes the most sense to switch the workflow to Windows.
Do many add-on developers develop on linux?
Since NVDA is a Windows app it makes more sense to me that we build with Windows on this repo.

**Comment by seanbudd** [comment]
@nvdaes ah - then we may run the risk that this also fails to build on the NV Access server. I will investigate this.

**Comment by seanbudd** [comment]
re-running CI

**Comment by seanbudd** [comment]
This has been registered now.
