### ISSUE TITLE
Not all add-ons get updated by crontab

### ISSUE THREAD

**Issue by XLTechie** [nvaccess/mrconfig#92]
@seanbudd

I was looking at the mrconfig file `automatic.crontab`.
There are many entries like:

```
#x  3 for addons starting with c
00  3 * * fri $AddonTranslationUpdate clipContentsDesigner
```
...
```
#x  4 for addons starting with d
```
...
```
04  4 * * fri $AddonTranslationUpdate dropbox
08  4 * * fri $AddonTranslationUpdate directLink
```

However, there are no entries for my add-ons `speechLogger` and `numpadNavMode`.

There is also no entry for `soundSplitter`, but that one may not be registered, as I only took it over recently, and don't know its full status yet.

Is this file not used any more? If it is used, why are some registered add-ons missing?
If some of mine are missing, what other ones might be missing?

**Comment by CyrilleB79** [comment]
Yes. Also TeleNVDA and nvdaRd, which were added recently are not in the cron table.

**Comment by seanbudd** [comment]
Hi, these all have been running on the server, I had just forgotten to commit and push these changes.

I have done so now: https://github.com/nvaccess/mrconfig/commit/12c079d0581f079f00fca570c12934a536b12c9b

I have also added a reminder note here: https://github.com/nvaccess/mrconfig/commit/9b5864f9416825ed4cad67727230077636b7c7b4

**Comment by seanbudd** [comment]
Can I close this issue?

**Comment by XLTechie** [comment]
Thanks @seanbudd. Closing.﻿

**Comment by CyrilleB79** [comment]
> Hi, these all have been running on the server, I had just forgotten to commit and push these changes.
> 
> I have done so now: [12c079d](https://github.com/nvaccess/mrconfig/commit/12c079d0581f079f00fca570c12934a536b12c9b)

Does it mean that the cron table on the server is not synchronized with the repo? This seems to contradict the two following lines found in `automatic.crontab`:
```
# Keep live crontab in sync with version control.
1 * * * * cd ${PathToMrRepo} && git pull -q && crontab automatic.crontab
```

Thanks to clarify.

**Comment by seanbudd** [comment]
Changes to the GitHub repository are pulled in, however changes I made directly to the server were never committed or pushed to the repository. As such, they were also not overwritten when pulling from the repo, as `automatic.crontab` had not been changed on GitHub, and unchanged files are not affected when pulling.
