### ISSUE TITLE
[Register add-on in translation system]: urlShortener

### ISSUE THREAD

**Issue by nvdaes** [nvaccess/mrconfig#94]
### Add-on name

urlShortener

### Add-on maintainer

@nvdaes

### Stable branch

- [X] Stable branch exists in add-on repo

**Comment by seanbudd** [comment]
Closed via https://github.com/nvaccess/mrconfig/commit/7dca6043f196713e16498466c7c42ad32acb52a8

**Comment by nvdaes** [comment]
@seanbudd , seems that this add-on hasn't an available.d file in mrconfig, and settings flag for translators is not available.
cc: @DraganRatkovich
Thanks for yourattention

**Comment by seanbudd** [comment]
Apologies that should be fixed now

**Comment by nvdaes** [comment]
Thanks. It's fixed now.

2023-04-20 2:08 GMT+02:00, Sean Budd ***@***.***>:

**Comment by nvdaes** [comment]
@seanbudd I think that some kind of issue maybe with translation updates for this add-on. The stable branch has 4 folders for docs but not locales.
We can wait until the next update, but in case you want to look at this before I point it out here.
Thanks.

**Comment by nvdaes** [comment]
Now locales are properly merged.
